# Generated by Django 3.2.18 on 2023-08-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger_api_client", "0005_auto_20220125_2035"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailuserro",
            name="postal_same_as_residential",
            field=models.BooleanField(default=False),
        ),     
        migrations.AlterField(
            model_name="emailuserro",
            name="billing_same_as_residential",
            field=models.BooleanField(default=False),
        ),           
        migrations.AlterField(
            model_name="datastore",
            name="data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="emailuser",
            name="ledger_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="emailuser",
            name="ledger_groups",
            field=models.JSONField(default=dict),
        ),
    ]
